language: ruby
rvm:
- 2.1.5
deploy:
  provider: heroku
  api_key:
    secure: <%= ENV['API_KEY_SECURE'] %>
  run:
  - rake db:migrate
  app: instmovie
  on:
    repo: netguru-training/instmovie
before_script:
- export RAILS_ENV=test
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
script:
- bundle exec rspec spec
